###
POST http://localhost:8080/api/v1/account/password-reset/acquire
Content-Type: application/json

{
  "redirectUrl": "http://localhost:3000/reset-password",
  "email": "kbratko@algebra.com"
}

###
POST http://localhost:8080/api/v1/account/password-reset
Content-Type: application/json

{
  "token": "c6d5fd84-4f7c-40ff-8b42-1ff952c6ca8b",
  "newPassword": "Pa$$w0rd"
}