version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "domace"
      POSTGRES_USER: "hc4wdhjeq3czth9cfm5mcwp73r5j7hwg"
      POSTGRES_PASSWORD: "uuxzm9hohtcxxs2pbmhhrhzm7id61e5e"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH: "81thzwsqlnntn22x24m2asjw93parhh2:g3t310ltdcltcb9lwpjuofiic6ltnm95"
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  # prometheus and grafana need to be configured, they do not work properly
  prometheus:
    image: registry.access.redhat.com/openshift3/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/:Z
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
