version: '3.9'

services:
  # database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "instakt"
      POSTGRES_USER: "hc4wdhjeq3czth9cfm5mcwp73r5j7hwg"
      POSTGRES_PASSWORD: "uuxzm9hohtcxxs2pbmhhrhzm7id61e5e"
    ports:
      - "5432:5432"
  db_manager:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  # prometheus and grafana need to be configured, they do not work properly
  prometheus:
    image: registry.access.redhat.com/openshift3/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/:Z
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana


  # seaweedfs
  master:
    image: chrislusf/seaweedfs
    ports:
      - "9333:9333"
      - "19333:19333"
      - "9324:9324"
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
  volume:
    image: chrislusf/seaweedfs
    ports:
      - "8082:8080"
      - "18080:18080"
      - "9325:9325"
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs
    ports:
      - "8888:8888"
      - "18888:18888"
      - "9326:9326"
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs
    ports:
      - "8333:8333"
      - "9327:9327"
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -config /config.json'
    volumes:
      - './seaweedfs/config.json:/config.json:Z'
    depends_on:
      - master
      - volume
      - filer

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
