version: '3.9'

services:
  # database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "instakt"
      POSTGRES_USER: "hc4wdhjeq3czth9cfm5mcwp73r5j7hwg"
      POSTGRES_PASSWORD: "uuxzm9hohtcxxs2pbmhhrhzm7id61e5e"
    ports:
      - "5432:5432"
  db_manager:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  # mailing
  mailtrap:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH: "81thzwsqlnntn22x24m2asjw93parhh2:g3t310ltdcltcb9lwpjuofiic6ltnm95"
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # seaweedfs
  master:
    image: chrislusf/seaweedfs
    ports:
      - "9333:9333"
      - "19333:19333"
      - "9324:9324"
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
  volume:
    image: chrislusf/seaweedfs
    ports:
      - "8082:8080"
      - "18080:18080"
      - "9325:9325"
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8082 -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs
    ports:
      - "8888:8888"
      - "18888:18888"
      - "9326:9326"
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs
    ports:
      - "8333:8333"
      - "9327:9327"
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -config /config.json'
    volumes:
      - './seaweedfs/config.json:/config.json:Z'
    depends_on:
      - master
      - volume
      - filer

volumes:
  prometheus-data:
