###
GET http://localhost:8080/api/v1/account/profile/social
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
POST http://localhost:8080/api/v1/account/profile/social
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "platform": "LinkedIn",
  "url": "https://www.linkedin.com/in/karlo-bratko/"
}

###
PUT http://localhost:8080/api/v1/account/profile/social/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "platform": "LinkedIn",
  "url": "https://www.linkedin.com/in/karlo-bratko/"
}

###
DELETE http://localhost:8080/api/v1/account/profile/social/1
Content-Type: application/json
Authorization: Bearer {{access_token}}