###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "kbratko",
  "email": "kbratko@algebra.com",
  "password": "Pa$$w0rd",
  "role": "User",
  "redirectUrl": "http://localhost:3000/confirm-registration"
}

###
POST http://localhost:8080/api/v1/auth/register/confirm
Content-Type: application/json

{
  "token": "dab3913c-22c6-4442-9e64-784e0f290ecf"
}

###
POST http://localhost:8080/api/v1/auth/register/reset
Content-Type: application/json

{
  "type": "token",
  "token": "dab3913c-22c6-4442-9e64-784e0f290ecf",
  "redirectUrl": "http://localhost:3000/confirm-registration"
}

###
POST http://localhost:8080/api/v1/auth/register/reset
Content-Type: application/json

{
  "type": "email",
  "email": "kbratko@algebra.com",
  "redirectUrl": "http://localhost:3000/confirm-registration"
}
