###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "kbratko",
  "email": "kbratko@algebra.com",
  "firstName": "Karlo",
  "lastName": "Bratko",
  "password": "Pa$$w0rd",
  "role": "Regular",
  "redirectUrl": "http://localhost:3000/confirm-registration"
}

###
POST http://localhost:8080/api/v1/auth/register/confirm
Content-Type: application/json

{
  "token": "1aada623-008d-4f49-8b45-6874b5222c5f"
}

###
POST http://localhost:8080/api/v1/auth/register/reset
Content-Type: application/json

{
  "type": "token",
  "token": "1aada623-008d-4f49-8b45-6874b5222c5f",
  "redirectUrl": "http://localhost:3000/confirm-registration"
}

###
POST http://localhost:8080/api/v1/auth/register/reset
Content-Type: application/json

{
  "type": "email",
  "email": "kbratko@algebra.com",
  "redirectUrl": "http://localhost:3000/confirm-registration"
}
